ENG_TOKENS = [
    "Travel",
    "Food",
    "Books",
    "Fitness",
    "Nature",
    "Photography",
    "Music",
    "Art",
    "Cooking",
    "Hiking",
    "Fashion",
    "Sports",
    "Movies",
    "Technology",
    "Gaming",
    "Gardening",
    "Yoga",
    "Dancing",
    "Animals",
    "History",
    "Science",
    "Cars",
    "Makeup",
    "DIY",
    "Writing",
    "Pets",
    "Coffee",
    "Wine",
    "Astronomy",
    "Beach",
    "Health",
    "Adventure",
    "Skiing",
    "Snowboarding",
    "Surfing",
    "Shopping",
    "Running",
    "Cycling",
    "Painting",
    "Design",
    "Architecture",
    "Sustainable Living",
    "Vintage",
    "Board Games",
    "Meditation",
    "Comedy",
    "Tattoos",
    "Cosplay",
    "Diving",
    "Knitting",
    "Pottery",
    "Music Production",
    "Wildlife Conservation",
    "Volunteer Work",
    "Tattoos",
]

SPA_TOKENS = [
    "Viajar",
    "Comida",
    "Libros",
    "Fitness",
    "Naturaleza",
    "Fotografía",
    "Música",
    "Arte",
    "Cocina",
    "Senderismo",
    "Moda",
    "Deportes",
    "Películas",
    "Tecnología",
    "Videojuegos",
    "Jardinería",
    "Yoga",
    "Baile",
    "Animales",
    "Historia",
    "Ciencia",
    "Coches",
    "Maquillaje",
    "Hágalo usted mismo (DIY)",
    "Escritura",
    "Mascotas",
    "Café",
    "Vino",
    "Astronomía",
    "Playa",
    "Salud",
    "Aventura",
    "Esquí",
    "Snowboard",
    "Surf",
    "Compras",
    "Correr",
    "Ciclismo",
    "Pintura",
    "Diseño",
    "Arquitectura",
    "Vida sostenible",
    "Vintage",
    "Juegos de mesa",
    "Meditación",
    "Comedia",
    "Tatuajes",
    "Cosplay",
    "Buceo",
    "Tejer",
    "Cerámica",
    "Producción musical",
    "Conservación de la vida silvestre",
    "Trabajo voluntario",
]
